import { PrismaClient } from "@prisma/client";
import { hash } from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  // Catégories
  const categories = await Promise.all([
    prisma.category.upsert({
      where: { slug: "international" },
      update: { description: "Actualité internationale", order: 1 },
      create: { name: "International", slug: "international", description: "Actualité internationale", order: 1 },
    }),
    prisma.category.upsert({
      where: { slug: "politique" },
      update: { description: "Politique française", order: 2 },
      create: { name: "Politique", slug: "politique", description: "Politique française", order: 2 },
    }),
    prisma.category.upsert({
      where: { slug: "economie" },
      update: { description: "Économie et finance", order: 3 },
      create: { name: "Économie", slug: "economie", description: "Économie et finance", order: 3 },
    }),
    prisma.category.upsert({
      where: { slug: "societe" },
      update: { description: "Société et faits divers", order: 4 },
      create: { name: "Société", slug: "societe", description: "Société et faits divers", order: 4 },
    }),
    prisma.category.upsert({
      where: { slug: "culture" },
      update: { description: "Culture et arts", order: 5 },
      create: { name: "Culture", slug: "culture", description: "Culture et arts", order: 5 },
    }),
    prisma.category.upsert({
      where: { slug: "sport" },
      update: { description: "Actualité sportive", order: 6 },
      create: { name: "Sport", slug: "sport", description: "Actualité sportive", order: 6 },
    }),
    prisma.category.upsert({
      where: { slug: "sciences" },
      update: { description: "Sciences et technologies", order: 7 },
      create: { name: "Sciences", slug: "sciences", description: "Sciences et technologies", order: 7 },
    }),
    prisma.category.upsert({
      where: { slug: "planete" },
      update: { description: "Environnement et climat", order: 8 },
      create: { name: "Planète", slug: "planete", description: "Environnement et climat", order: 8 },
    }),
  ]);

  const [international, politique, economie, societe, culture, sport, sciences, planete] = categories;

  // Articles — 30 articles réalistes en français avec images Unsplash thématiques
  const articles = [
    {
      title: "L'Union européenne adopte un plan de défense commun à 150 milliards d'euros",
      slug: "ue-plan-defense-commun-150-milliards",
      excerpt: "Les Vingt-Sept se sont accordés sur un programme d'investissements militaires sans précédent, visant à renforcer l'autonomie stratégique du continent face aux menaces croissantes.",
      content: "<p>Les dirigeants européens ont conclu un accord historique lors du sommet extraordinaire de Bruxelles, jeudi 20 mars. Le plan « Bouclier européen », doté de 150 milliards d'euros sur sept ans, prévoit des investissements massifs dans la défense aérienne, la cybersécurité et les capacités de projection commune.</p><p>« Nous entrons dans une nouvelle ère de la défense européenne », a déclaré la présidente de la Commission, soulignant que ce programme permettra de mutualiser les efforts industriels et de combler les lacunes capacitaires identifiées depuis 2022.</p><p>Le plan prévoit notamment la création d'un quartier général opérationnel permanent, le développement de drones de combat européens et le renforcement des stocks de munitions. La France et l'Allemagne, moteurs de l'initiative, ont obtenu que 40 % des contrats soient réservés à l'industrie européenne.</p><p>Les États membres devront consacrer au minimum 2,5 % de leur PIB à la défense d'ici 2028, un seuil que seuls six pays atteignent actuellement. Le Parlement européen débattra du texte en séance plénière la semaine prochaine avant un vote formel prévu mi-avril.</p>",
      imageUrl: "https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Drapeaux européens devant le Parlement de Bruxelles",
      author: "Philippe Ricard",
      categoryId: international.id,
      tags: JSON.stringify(["Union européenne", "Défense", "Budget", "Diplomatie"]),
      publishedAt: new Date("2026-03-20T14:30:00"),
    },
    {
      title: "Sommet sur l'intelligence artificielle : les grandes puissances s'accordent sur un cadre éthique minimal",
      slug: "sommet-ia-cadre-ethique-grandes-puissances",
      excerpt: "Réunis à Genève, les représentants de quarante pays ont signé une déclaration commune sur les principes de gouvernance de l'IA, malgré des divergences profondes.",
      content: "<p>Après trois jours de négociations tendues, le sommet mondial sur l'intelligence artificielle s'est conclu par l'adoption d'une déclaration commune fixant des principes de base : transparence des algorithmes, interdiction des systèmes d'armes autonomes létales, et obligation de signaler les contenus générés par IA.</p><p>La Chine et les États-Unis, longtemps opposés sur la portée du texte, ont accepté un compromis sur la question de la surveillance. « Ce n'est qu'un premier pas, mais c'est un pas nécessaire », a commenté le secrétaire général des Nations unies.</p><p>Le texte crée également un comité d'experts indépendants chargé d'évaluer les risques des modèles d'IA dits « à double usage », susceptibles d'être détournés à des fins militaires ou de désinformation. Ce mécanisme d'évaluation, inspiré du GIEC pour le climat, se réunira deux fois par an.</p><p>Plusieurs ONG ont toutefois dénoncé le caractère non contraignant de la déclaration, qui ne prévoit aucune sanction pour les États qui ne respecteraient pas ses principes. Le prochain sommet est prévu à Séoul en novembre 2026.</p>",
      imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Interface d'intelligence artificielle sur écran",
      author: "Martin Untersinger",
      categoryId: international.id,
      tags: JSON.stringify(["Intelligence artificielle", "Diplomatie", "Régulation", "ONU"]),
      publishedAt: new Date("2026-03-19T10:15:00"),
    },
    {
      title: "Guerre en Ukraine : Moscou et Kiev acceptent un cessez-le-feu temporaire de trente jours",
      slug: "ukraine-cessez-le-feu-temporaire-trente-jours",
      excerpt: "Sous la médiation turque, les deux parties ont convenu d'une trêve humanitaire, la première depuis le début du conflit, pour permettre l'acheminement de l'aide aux civils.",
      content: "<p>Le cessez-le-feu, qui entrera en vigueur samedi à minuit, couvre l'ensemble de la ligne de front. Il prévoit la création de corridors humanitaires dans les régions de Kherson et de Zaporijia, ainsi qu'un échange de prisonniers de guerre.</p><p>Les observateurs restent prudents. « Les violations sont probables dans les premières heures, mais le mécanisme de surveillance mis en place avec la Croix-Rouge internationale devrait permettre de maintenir la pression », analyse un diplomate occidental sous couvert d'anonymat.</p><p>Le président Zelensky a insisté sur le fait que cette trêve ne préjuge en rien des négociations territoriales à venir. Moscou, de son côté, présente l'accord comme une « mesure humanitaire unilatérale » plutôt que comme une concession diplomatique.</p><p>L'Union européenne a promis de débloquer 500 millions d'euros d'aide humanitaire supplémentaire dans le cadre de cette trêve, destinés notamment à la reconstruction des infrastructures civiles endommagées.</p>",
      imageUrl: "https://images.unsplash.com/photo-1655720033654-a4239dd42d10?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Drapeau ukrainien dans une ville en reconstruction",
      author: "Rémy Ourdan",
      categoryId: international.id,
      tags: JSON.stringify(["Ukraine", "Russie", "Guerre", "Diplomatie", "Humanitaire"]),
      publishedAt: new Date("2026-03-18T16:45:00"),
    },
    {
      title: "Réforme des retraites : le gouvernement ouvre la voie à des aménagements pour les carrières longues",
      slug: "reforme-retraites-amenagements-carrieres-longues",
      excerpt: "Le premier ministre a annoncé une série de mesures correctrices pour répondre aux critiques persistantes sur l'équité du système de retraite réformé en 2023.",
      content: "<p>Trois ans après l'adoption de la réforme contestée, le gouvernement reconnaît la nécessité d'ajustements. Les travailleurs ayant commencé avant 18 ans pourront désormais partir à 61 ans au lieu de 62, et un dispositif de pénibilité renforcé est prévu pour les métiers les plus exposés.</p><p>Les syndicats, tout en saluant « un premier geste », maintiennent leur demande d'abrogation complète de la réforme. La CGT a d'ores et déjà appelé à une journée de mobilisation le 15 avril.</p><p>Le dispositif « carrières longues » concernerait environ 120 000 assurés par an, soit un coût estimé à 800 millions d'euros pour les finances publiques. Ce financement sera assuré par une légère hausse des cotisations patronales, a précisé le ministre du Travail.</p><p>L'opposition de gauche a dénoncé des « mesures cosmétiques » qui ne remettent pas en cause le report de l'âge légal à 64 ans. Le Rassemblement national, qui avait voté la motion de censure contre la réforme, réclame quant à lui un référendum.</p>",
      imageUrl: "https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Manifestants avec des pancartes lors d'une mobilisation syndicale",
      author: "Raphaëlle Besse Desmoulières",
      categoryId: politique.id,
      tags: JSON.stringify(["Retraites", "Syndicats", "Social", "Gouvernement"]),
      publishedAt: new Date("2026-03-21T08:00:00"),
    },
    {
      title: "Élections régionales : la gauche unie progresse dans les sondages à six mois du scrutin",
      slug: "elections-regionales-gauche-unie-sondages",
      excerpt: "L'alliance entre socialistes, écologistes et insoumis semble porter ses fruits dans plusieurs régions clés, selon les dernières enquêtes d'opinion.",
      content: "<p>À six mois des élections régionales de septembre, les sondages dessinent une dynamique favorable à la gauche unie. En Île-de-France, l'alliance progressiste atteint 34 % des intentions de vote au premier tour, contre 28 % pour la droite et 22 % pour le Rassemblement national.</p><p>En Provence-Alpes-Côte d'Azur et en Hauts-de-France, les configurations sont plus ouvertes, avec des triangulaires probables au second tour.</p><p>La stratégie d'union, qui avait échoué aux législatives de 2024 sur fond de dissensions programmatiques, semble désormais plus solide. Les partis de gauche se sont accordés sur une liste commune et un programme commun dans douze des treize régions métropolitaines.</p><p>Reste à transformer l'essai dans les urnes. Les analystes rappellent que les élections régionales obéissent à des logiques locales fortes et que les scrutins de mars sont traditionnellement marqués par une forte abstention, qui pourrait avantager ou pénaliser les différentes forces en présence.</p>",
      imageUrl: "https://images.unsplash.com/photo-1540910419892-4a36d2c3266c?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Urnes de vote dans un bureau électoral",
      author: "Alexandre Lemarié",
      categoryId: politique.id,
      tags: JSON.stringify(["Élections", "Sondages", "Gauche", "Régions"]),
      publishedAt: new Date("2026-03-20T11:30:00"),
    },
    {
      title: "Le Parlement adopte une loi sur la régulation des réseaux sociaux pour les mineurs",
      slug: "loi-regulation-reseaux-sociaux-mineurs",
      excerpt: "Le texte impose aux plateformes la vérification de l'âge et interdit l'accès aux moins de 15 ans sans consentement parental, sous peine de lourdes amendes.",
      content: "<p>Adoptée à une large majorité, la loi « Protection numérique des mineurs » contraint les plateformes à mettre en place des systèmes de vérification d'âge certifiés par la CNIL. Les contrevenants s'exposent à des amendes pouvant atteindre 6 % de leur chiffre d'affaires mondial.</p><p>Meta, TikTok et Snap ont exprimé leurs réserves sur la faisabilité technique du dispositif, tandis que les associations de protection de l'enfance ont salué « une avancée majeure ».</p><p>La loi prévoit également une période de transition de dix-huit mois pour permettre aux plateformes de mettre en place les outils techniques nécessaires. Durant cette période, elles devront proposer un mode « mineur » restreignant l'accès à certains contenus.</p><p>La CNIL sera chargée de certifier les solutions de vérification d'âge et disposera d'un pouvoir d'injonction pour contraindre les plateformes récalcitrantes. Des associations de parents ont participé activement à la rédaction du texte dans le cadre d'une consultation publique menée en 2025.</p>",
      imageUrl: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Jeune adolescent utilisant un smartphone",
      author: "Alexandre Piquard",
      categoryId: politique.id,
      tags: JSON.stringify(["Numérique", "Réseaux sociaux", "Mineurs", "Législation"]),
      publishedAt: new Date("2026-03-17T19:00:00"),
    },
    {
      title: "La BCE maintient ses taux directeurs et signale une pause prolongée",
      slug: "bce-maintien-taux-directeurs-pause",
      excerpt: "La Banque centrale européenne a décidé de maintenir son taux de dépôt à 2,5 %, estimant que l'inflation sous-jacente reste trop élevée pour justifier une nouvelle baisse.",
      content: "<p>Christine Lagarde a souligné lors de sa conférence de presse que « les risques inflationnistes persistent, notamment dans le secteur des services ». La BCE anticipe une inflation de 2,3 % en 2026, légèrement au-dessus de son objectif de 2 %.</p><p>Les marchés, qui espéraient un signal plus accommodant, ont réagi négativement : l'euro s'est renforcé face au dollar et les indices boursiers européens ont cédé en moyenne 0,8 %.</p><p>Les économistes soulignent que la BCE se trouve dans une position délicate : d'un côté, l'économie européenne montre des signes de ralentissement qui plaident pour une baisse des taux ; de l'autre, les tensions géopolitiques et la hausse des dépenses de défense alimentent des pressions inflationnistes.</p><p>La prochaine réunion du Conseil des gouverneurs est prévue le 12 juin. D'ici là, la BCE surveillera de près les données sur les salaires et les marges des entreprises, deux indicateurs jugés clés pour évaluer la persistance de l'inflation dans les services.</p>",
      imageUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Graphique de cours boursiers sur écran",
      author: "Éric Albert",
      categoryId: economie.id,
      tags: JSON.stringify(["BCE", "Taux directeurs", "Inflation", "Euro"]),
      publishedAt: new Date("2026-03-20T15:00:00"),
    },
    {
      title: "Le marché immobilier français montre des signes de reprise après deux ans de crise",
      slug: "marche-immobilier-reprise-france",
      excerpt: "Les transactions repartent à la hausse au premier trimestre 2026, portées par la baisse des taux de crédit et un ajustement des prix dans les grandes métropoles.",
      content: "<p>Selon les chiffres des notaires publiés jeudi, le nombre de transactions immobilières a progressé de 12 % au premier trimestre par rapport à la même période de 2025. Les prix, en revanche, restent en recul de 5 à 8 % dans les grandes villes par rapport à leur pic de 2022.</p><p>Paris fait figure d'exception avec une stabilisation autour de 9 200 euros le mètre carré, après avoir perdu près de 15 % en deux ans.</p><p>La baisse des taux de crédit immobilier, qui sont passés de 4,2 % à fin 2024 à 3,4 % en mars 2026, explique en grande partie ce regain d'activité. Le pouvoir d'achat immobilier des ménages s'est amélioré de 8 % sur un an.</p><p>Les professionnels du secteur restent cependant prudents : « Nous sommes sur une reprise fragile, pas sur un retour en force du marché », prévient le président de la FNAIM. La hausse des droits de mutation dans plusieurs départements, décidée en 2025 pour combler les déficits des collectivités, pourrait freiner la dynamique.</p>",
      imageUrl: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Façades d'immeubles haussmanniens à Paris",
      author: "Isabelle Rey-Lefebvre",
      categoryId: economie.id,
      tags: JSON.stringify(["Immobilier", "Taux de crédit", "Logement", "Paris"]),
      publishedAt: new Date("2026-03-19T09:00:00"),
    },
    {
      title: "Airbus dépasse Boeing en commandes pour la cinquième année consécutive",
      slug: "airbus-depasse-boeing-commandes-cinquieme-annee",
      excerpt: "L'avionneur européen a engrangé 1 850 commandes nettes en 2025, consolidant sa domination sur le marché mondial de l'aviation commerciale.",
      content: "<p>Airbus confirme sa position de leader mondial avec un carnet de commandes record de plus de 8 600 appareils. Le succès de la famille A320neo, particulièrement prisée des compagnies low-cost et moyen-courrier, explique l'essentiel de cette performance.</p><p>Boeing, de son côté, peine à retrouver la confiance du marché après les crises successives liées au 737 MAX et aux problèmes de qualité de production.</p><p>Le PDG d'Airbus, Guillaume Faury, a annoncé une montée en cadence de la production : l'objectif est d'assembler 75 A320 par mois d'ici fin 2027, contre 55 actuellement. Cette accélération nécessite un investissement massif dans les lignes d'assemblage de Toulouse et Hambourg.</p><p>La filière des fournisseurs reste toutefois sous tension. Plusieurs équipementiers peinent à suivre la cadence et ont prévenu qu'ils ne pourraient pas garantir leurs livraisons au-delà de 65 appareils par mois sans investissements supplémentaires en capacité de production.</p>",
      imageUrl: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Avion Airbus en approche finale sur une piste d'atterrissage",
      author: "Guy Dutheil",
      categoryId: economie.id,
      tags: JSON.stringify(["Airbus", "Aviation", "Industrie", "Boeing"]),
      publishedAt: new Date("2026-03-18T11:00:00"),
    },
    {
      title: "Canicule précoce : alerte orange dans huit départements du sud de la France",
      slug: "canicule-precoce-alerte-orange-sud-france",
      excerpt: "Des températures dépassant 35 °C sont attendues dès ce week-end dans le Midi, un phénomène inhabituel pour un mois de mars, selon Météo-France.",
      content: "<p>Météo-France a placé huit départements en alerte orange canicule, de l'Hérault aux Bouches-du-Rhône. Les températures pourraient atteindre 37 °C samedi, battant les records de chaleur pour un mois de mars établis en 2023.</p><p>Les autorités sanitaires recommandent aux personnes vulnérables de limiter leurs déplacements et de s'hydrater régulièrement. Les préfectures ont activé les plans « chaleur » dans les Ehpad et les hôpitaux.</p><p>Cet épisode exceptionnel est lié à un anticyclone puissant venu d'Afrique du Nord, qui compresse et réchauffe les masses d'air en descendant sur le versant sud du Massif central. Les météorologues précisent que de tels épisodes, rares en mars il y a vingt ans, tendent à se multiplier sous l'effet du réchauffement climatique.</p><p>Les pompiers du Var et des Bouches-du-Rhône ont été placés en vigilance maximale en raison du risque d'incendies de forêt, malgré la saison inhabituelle. La végétation, particulièrement sèche après un hiver peu pluvieux, présente des conditions propices à la propagation du feu.</p>",
      imageUrl: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Thermomètre sous un soleil éclatant",
      author: "Stéphane Mandard",
      categoryId: societe.id,
      tags: JSON.stringify(["Canicule", "Météo", "Santé", "Climat"]),
      publishedAt: new Date("2026-03-21T07:30:00"),
    },
    {
      title: "Éducation : la France recule encore dans le classement PISA en mathématiques",
      slug: "education-france-recul-classement-pisa-mathematiques",
      excerpt: "Les résultats de l'enquête PISA 2025 confirment la tendance baissière des performances des élèves français, désormais en dessous de la moyenne de l'OCDE.",
      content: "<p>Avec un score moyen de 468 points en mathématiques (contre 472 en 2022 et 495 en 2018), la France poursuit sa glissade dans le classement international. Le rapport pointe les inégalités sociales persistantes : l'écart entre les élèves les plus favorisés et les plus défavorisés reste l'un des plus élevés de l'OCDE.</p><p>Le ministre de l'Éducation a annoncé un plan de « remise à niveau » incluant le dédoublement des classes de mathématiques au collège et la revalorisation de la filière enseignante.</p><p>Les enseignants, par la voix de leurs syndicats, ont accueilli ces annonces avec scepticisme. « On nous dit chaque année qu'il faut revaloriser le métier, mais les actes ne suivent pas les discours », a déclaré la secrétaire générale du SNES-FSU. Le syndicat réclame une hausse de 30 % des salaires en début de carrière.</p><p>Parmi les pays qui progressent dans PISA, les chercheurs citent le Japon, la Corée du Sud et l'Estonie, dont les systèmes éducatifs reposent sur une formation initiale des enseignants plus longue et plus sélective. Ces exemples nourrissent le débat sur la réforme de l'INSPE en France.</p>",
      imageUrl: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Élèves dans une salle de classe en train de travailler",
      author: "Violaine Morin",
      categoryId: societe.id,
      tags: JSON.stringify(["Éducation", "PISA", "Mathématiques", "École"]),
      publishedAt: new Date("2026-03-19T14:00:00"),
    },
    {
      title: "Le nombre de sans-abri en France atteint un niveau record, selon la Fondation Abbé-Pierre",
      slug: "sans-abri-france-record-fondation-abbe-pierre",
      excerpt: "Le rapport annuel de la Fondation dénombre plus de 330 000 personnes sans domicile fixe, une augmentation de 15 % en deux ans.",
      content: "<p>La Fondation Abbé-Pierre tire la sonnette d'alarme dans son 32e rapport sur le mal-logement. Le nombre de personnes sans domicile a atteint 330 000, dont 45 000 enfants. L'augmentation est particulièrement marquée en Île-de-France et dans les grandes métropoles régionales.</p><p>Le rapport préconise la construction de 150 000 logements sociaux par an et la réquisition des logements vacants dans les zones tendues.</p><p>Parmi les profils les plus touchés, on trouve des travailleurs pauvres dont les salaires ne suffisent plus à couvrir les loyers dans les grandes agglomérations, ainsi que des personnes âgées dont les retraites modestes ne leur permettent pas de faire face à la hausse des charges.</p><p>Le gouvernement a rappelé le plan quinquennal « Logement d'abord » lancé en 2022, qui a permis d'héberger 180 000 personnes. Mais la Fondation estime que ce rythme est « insuffisant » face à la dégradation de la situation. Elle appelle à une mobilisation nationale d'urgence, comparable au plan Juppé de 1995.</p>",
      imageUrl: "https://images.unsplash.com/photo-1518398046080-af3e4c76d2c8?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Tente et affaires d'une personne sans-abri sur un trottoir urbain",
      author: "Sylvia Zappi",
      categoryId: societe.id,
      tags: JSON.stringify(["Logement", "Sans-abri", "Pauvreté", "Social"]),
      publishedAt: new Date("2026-03-17T10:30:00"),
    },
    {
      title: "Cannes 2026 : Jacques Audiard présidera le jury du 79e Festival",
      slug: "cannes-2026-jacques-audiard-president-jury",
      excerpt: "Le cinéaste français, Palme d'or en 2024, dirigera le jury de la compétition officielle. Une première pour un réalisateur français depuis 2014.",
      content: "<p>Jacques Audiard, couronné pour « Emilia Pérez » en 2024, succède à Greta Gerwig à la présidence du jury. « C'est un honneur immense et une responsabilité que j'aborde avec humilité », a déclaré le réalisateur dans un communiqué.</p><p>Le festival, qui se tiendra du 12 au 23 mai, a également dévoilé les premiers noms de la sélection officielle, avec des films très attendus de Wong Kar-wai, Céline Sciamma et Bong Joon-ho.</p><p>Le jury sera composé de neuf membres issus de cinq continents, dont l'actrice brésilienne Fernanda Torres, le réalisateur iranien Asghar Farhadi et la productrice britannique Andrea Arnold. La parité hommes-femmes est respectée pour la troisième année consécutive.</p><p>Cette édition marquera également le retour de la section « Un Certain Regard » dans sa forme originale, avec un jury autonome et une cérémonie de remise des prix distincte. Cannes 2026 rendra hommage au cinéma africain à l'occasion du 60e anniversaire de la Semaine de la critique.</p>",
      imageUrl: "https://images.unsplash.com/photo-1478720568477-152d9b164e26?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Tapis rouge d'un festival de cinéma avec photographes",
      author: "Mathieu Macheret",
      categoryId: culture.id,
      tags: JSON.stringify(["Cannes", "Cinéma", "Festival", "Palme d'or"]),
      publishedAt: new Date("2026-03-21T10:00:00"),
    },
    {
      title: "Le Louvre bat un nouveau record de fréquentation avec 11,2 millions de visiteurs en 2025",
      slug: "louvre-record-frequentation-2025",
      excerpt: "Le musée parisien a dépassé son précédent record de 2018, porté par l'exposition événement consacrée à Vermeer et la réouverture de l'aile Richelieu rénovée.",
      content: "<p>Avec 11,2 millions d'entrées en 2025, le Louvre confirme son statut de musée le plus visité au monde. L'exposition « Vermeer, maître de la lumière », qui a attiré à elle seule 1,4 million de visiteurs entre septembre et décembre, a contribué significativement à ce résultat.</p><p>La direction du musée a annoncé la mise en place d'un système de réservation obligatoire pour 2026, afin de mieux répartir les flux de visiteurs.</p><p>Le Louvre entend également développer son offre numérique, avec la mise en ligne d'une visite virtuelle en réalité augmentée de l'ensemble des collections permanentes d'ici fin 2026. Cette initiative, cofinancée par le ministère de la Culture, vise à toucher un public mondial qui ne peut pas se déplacer à Paris.</p><p>Les chiffres de fréquentation masquent toutefois des disparités : 70 % des visiteurs sont étrangers, et seuls 30 % ont moins de 26 ans. Le musée travaille à renforcer son lien avec les publics scolaires français, avec un objectif de 500 000 visites scolaires par an d'ici 2028.</p>",
      imageUrl: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=800&q=80&auto=format&fit=crop",
      imageAlt: "La pyramide du Louvre illuminée la nuit",
      author: "Philippe Dagen",
      categoryId: culture.id,
      tags: JSON.stringify(["Louvre", "Musée", "Exposition", "Paris", "Tourisme"]),
      publishedAt: new Date("2026-03-18T12:00:00"),
    },
    {
      title: "Le nouveau roman de Leïla Slimani explore les racines de la violence coloniale",
      slug: "leila-slimani-nouveau-roman-violence-coloniale",
      excerpt: "Avec « Les Jardins de cendres », l'écrivaine franco-marocaine livre une fresque familiale ambitieuse sur trois générations, entre Casablanca et Paris.",
      content: "<p>Publié chez Gallimard, « Les Jardins de cendres » conclut la trilogie commencée avec « Le Pays des autres ». Leïla Slimani y retrace le destin d'une famille marocaine de l'indépendance à nos jours, interrogeant les héritages de la colonisation et les identités multiples.</p><p>La critique est unanime : « Un chef-d'œuvre de sensibilité et de précision historique », écrit Le Figaro littéraire. Le livre est donné favori pour le prix Goncourt 2026.</p><p>Dans ce roman fleuve de 650 pages, l'auteure brosse le portrait d'une femme berbère, Mathilde, qui a épousé un officier de l'armée française au lendemain de la Seconde Guerre mondiale et suit son destin jusqu'à nos jours. Une saga sur l'appartenance, la mémoire et les cicatrices que l'histoire laisse dans les corps et les âmes.</p><p>« J'ai voulu montrer que le colonialisme n'est pas une période révolue, c'est une blessure toujours ouverte qui se transmet de génération en génération », explique Leïla Slimani dans une interview accordée au Monde des livres. Le roman paraît simultanément en dix-sept langues.</p>",
      imageUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Livres ouverts sur une table en bois",
      author: "Florence Bouchy",
      categoryId: culture.id,
      tags: JSON.stringify(["Littérature", "Roman", "Colonisation", "Goncourt"]),
      publishedAt: new Date("2026-03-16T09:00:00"),
    },
    {
      title: "Ligue 1 : le PSG s'impose dans le classique face à l'OM et prend le large en tête",
      slug: "ligue-1-psg-om-classique-victoire",
      excerpt: "Grâce à des buts de Dembélé et Kang-in Lee, le Paris Saint-Germain s'est imposé 2-0 au Vélodrome et compte désormais onze points d'avance.",
      content: "<p>Dans un Vélodrome bouillant, le PSG a fait parler sa supériorité technique. Ousmane Dembélé a ouvert le score d'une frappe enroulée à la 23e minute, avant que Kang-in Lee ne double la mise sur un contre éclair en seconde période (67e).</p><p>Avec cette 25e victoire en 28 journées, le club parisien file vers un treizième titre de champion de France, le quatrième consécutif sous l'ère Luis Enrique.</p><p>L'entraîneur parisien s'est montré satisfait mais exigeant après la rencontre : « On a contrôlé le match, mais on doit être plus efficaces en contre-attaque. Nous avons eu cinq occasions franches que nous n'avons pas concrétisées. » Son équipe affronte Dortmund en quart de finale de Ligue des champions le 8 avril.</p><p>Du côté marseillais, la déception est grande. L'OM, qui rêvait de revenir dans la course au titre, voit l'écart se creuser dangereusement. Son entraîneur a annoncé un « bilan collectif » dans la semaine pour analyser les raisons d'une telle désillusion à domicile.</p>",
      imageUrl: "https://images.unsplash.com/photo-1543326727-cf6c39e8f84c?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Stade de football plein de supporters sous les projecteurs",
      author: "Rémi Dupré",
      categoryId: sport.id,
      tags: JSON.stringify(["PSG", "Ligue 1", "Football", "Classique"]),
      publishedAt: new Date("2026-03-21T00:30:00"),
    },
    {
      title: "Roland-Garros : le tournoi innove avec un toit rétractable sur le court Suzanne-Lenglen",
      slug: "roland-garros-toit-retractable-suzanne-lenglen",
      excerpt: "Après le court Philippe-Chatrier en 2020, la Fédération française de tennis équipe son deuxième plus grand court d'une couverture amovible.",
      content: "<p>Le nouveau toit, d'un coût de 80 millions d'euros, sera opérationnel pour l'édition 2026 du tournoi. Cette structure en acier et verre de 6 200 mètres carrés peut s'ouvrir ou se fermer en quinze minutes.</p><p>« Roland-Garros rattrape son retard sur les autres Grand Chelem », a commenté la présidente de la FFT. L'Open d'Australie et l'US Open disposent déjà de toits sur leurs deux courts principaux.</p><p>La Fédération française de tennis a profité de cette inauguration pour dévoiler son plan de développement à dix ans, qui prévoit également la rénovation des courts annexes et la création d'un espace muséographique dédié à l'histoire du tennis français.</p><p>Pour les joueurs, ce toit change fondamentalement les conditions de jeu sur terre battue : l'absence de vent et d'humidité favorise les gros frappeurs et les joueurs de fond de court au détriment des joueurs de finesse. Une adaptation tactique que les entraîneurs commencent déjà à intégrer dans leur préparation.</p>",
      imageUrl: "https://images.unsplash.com/photo-1554068865-24ceec697ef1?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Court de tennis en terre battue vu de haut",
      author: "Franck Ramella",
      categoryId: sport.id,
      tags: JSON.stringify(["Roland-Garros", "Tennis", "Grand Chelem", "Infrastructure"]),
      publishedAt: new Date("2026-03-19T16:00:00"),
    },
    {
      title: "JO 2030 : les Alpes françaises dévoilent le plan de mobilité durable pour les épreuves",
      slug: "jo-2030-alpes-mobilite-durable",
      excerpt: "Le comité d'organisation mise sur le rail et les navettes électriques pour limiter l'empreinte carbone des Jeux olympiques d'hiver.",
      content: "<p>Le plan de transport présenté prévoit un réseau de navettes électriques entre les sites de compétition et un renforcement massif des lignes TGV et TER. L'objectif est de limiter à 20 % la part du transport routier individuel, contre 60 % habituellement pour ce type d'événement.</p><p>Les organisateurs promettent également 100 % d'énergie renouvelable pour alimenter les sites olympiques, grâce à des contrats avec des producteurs d'hydroélectricité alpine.</p><p>Le village olympique, qui accueillera 3 000 athlètes à Albertville, sera construit selon les normes de construction passive les plus exigeantes, avec une empreinte carbone inférieure de 60 % aux constructions standard. Après les Jeux, les logements seront reconvertis en résidences étudiantes et en logements sociaux.</p><p>Les associations de protection des paysages alpins surveillent de près ces engagements. Elles ont obtenu que tout nouveau tracé de piste ou d'installation soit soumis à une étude d'impact environnemental indépendante, avec possibilité de recours devant le tribunal administratif.</p>",
      imageUrl: "https://images.unsplash.com/photo-1578924825700-32f39db4d3f6?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Skieurs sur une piste alpine enneigée",
      author: "Clément Guillou",
      categoryId: sport.id,
      tags: JSON.stringify(["JO 2030", "Jeux olympiques", "Alpes", "Mobilité durable"]),
      publishedAt: new Date("2026-03-17T08:00:00"),
    },
    {
      title: "Une nouvelle thérapie génique guérit la drépanocytose chez 90 % des patients traités",
      slug: "therapie-genique-drepanocytose-resultats",
      excerpt: "Les résultats de l'essai clinique de phase 3, publiés dans le New England Journal of Medicine, ouvrent la voie à un traitement curatif de cette maladie génétique.",
      content: "<p>L'essai, mené sur 120 patients dans quinze centres hospitaliers, montre une rémission complète chez 90 % des sujets traités, sans rechute après trois ans de suivi. La thérapie, basée sur la technologie CRISPR-Cas9, corrige directement la mutation responsable de la maladie dans les cellules souches du patient.</p><p>Le coût du traitement, estimé à 2,1 millions d'euros par patient, pose toutefois la question de l'accès équitable, notamment en Afrique subsaharienne où la maladie est la plus répandue.</p><p>L'Agence européenne des médicaments (EMA) a accordé une procédure d'évaluation accélérée au traitement, développé conjointement par l'AP-HP et la biotech française Genopole. Une autorisation de mise sur le marché pourrait être obtenue dès fin 2026.</p><p>La Haute Autorité de santé a d'ores et déjà été saisie pour évaluer les conditions de remboursement par l'Assurance maladie. Face au coût considérable, plusieurs économistes de la santé proposent un modèle de paiement à l'efficacité : le laboratoire ne percevrait l'intégralité de la somme qu'en cas de guérison effective.</p>",
      imageUrl: "https://images.unsplash.com/photo-1532187863486-abf9dbad1b69?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Chercheur travaillant dans un laboratoire de biologie moléculaire",
      author: "Sandrine Cabut",
      categoryId: sciences.id,
      tags: JSON.stringify(["Thérapie génique", "CRISPR", "Médecine", "Recherche"]),
      publishedAt: new Date("2026-03-20T06:00:00"),
    },
    {
      title: "La mission Artemis IV réussit le premier alunissage habité depuis 1972",
      slug: "artemis-iv-alunissage-habite-lune",
      excerpt: "Deux astronautes américains ont foulé le sol lunaire dans la région du pôle Sud, marquant le retour de l'humanité sur la Lune après plus de cinquante ans.",
      content: "<p>Le module Starship HLS s'est posé dans le cratère Shackleton à 15 h 42 (heure de Paris), après un voyage de quatre jours. Les astronautes Jessica Watkins et Michael Lopez-Alegria ont effectué une sortie extravéhiculaire de six heures pour collecter des échantillons de glace dans les zones d'ombre permanente.</p><p>« Un petit pas pour l'homme, un bond de géant pour l'exploration durable de l'espace », a déclaré la commandante Watkins, en écho aux mots de Neil Armstrong. La NASA prévoit l'installation d'une base lunaire permanente d'ici 2032.</p><p>Les deux astronautes ont déployé un réseau de capteurs sismiques et un télescope miniature pointé vers le centre de la galaxie. Ces instruments, alimentés par des panneaux solaires, transmettront des données pendant au moins dix ans.</p><p>L'Agence spatiale européenne, qui a fourni le module de service d'Orion, travaille déjà sur sa contribution à la future base lunaire : un module d'habitat pressurisé et un rover d'exploration prévu pour la mission Artemis VI en 2029. La Chine, qui vise son propre alunissage habité pour 2030, a salué « une prouesse technique remarquable ».</p>",
      imageUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Vue de la Lune depuis l'espace",
      author: "Pierre Barthélémy",
      categoryId: sciences.id,
      tags: JSON.stringify(["NASA", "Lune", "Espace", "Artemis"]),
      publishedAt: new Date("2026-03-15T18:00:00"),
    },
    {
      title: "Des chercheurs français découvrent un mécanisme clé dans la maladie d'Alzheimer",
      slug: "alzheimer-decouverte-mecanisme-chercheurs-francais",
      excerpt: "L'équipe de l'Inserm a identifié une protéine qui accélère la propagation des plaques amyloïdes, ouvrant de nouvelles pistes thérapeutiques.",
      content: "<p>La protéine TDP-43, déjà connue dans d'autres maladies neurodégénératives, jouerait un rôle central dans la propagation des plaques amyloïdes caractéristiques d'Alzheimer. L'étude, publiée dans Nature Neuroscience, montre que son inhibition réduit de 60 % la formation de plaques chez la souris.</p><p>« Si ces résultats se confirment chez l'humain, nous pourrions disposer d'un traitement préventif d'ici dix ans », estime le professeur Luc Bhatt, directeur de l'étude à l'Inserm de Bordeaux.</p><p>La découverte ouvre la voie à une approche thérapeutique radicalement différente des traitements actuels, qui cherchent à éliminer les plaques déjà formées. En bloquant TDP-43, on agirait en amont, avant même que la dégénérescence neurologique ne commence.</p><p>L'équipe travaille désormais au développement d'un inhibiteur de TDP-43 administrable par voie orale. Un premier essai de toxicité sur le primate est prévu pour le second semestre 2026. En France, 1,2 million de personnes sont atteintes d'Alzheimer, et ce chiffre devrait doubler d'ici 2050 avec le vieillissement de la population.</p>",
      imageUrl: "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Image IRM d'un cerveau humain",
      author: "Hervé Morin",
      categoryId: sciences.id,
      tags: JSON.stringify(["Alzheimer", "Inserm", "Neurosciences", "Recherche"]),
      publishedAt: new Date("2026-03-14T07:00:00"),
    },
    {
      title: "Climat : les émissions mondiales de CO2 ont atteint un nouveau pic en 2025",
      slug: "emissions-co2-mondial-pic-2025",
      excerpt: "Malgré la croissance des énergies renouvelables, les émissions de gaz à effet de serre ont augmenté de 1,1 % l'an dernier, selon le Global Carbon Project.",
      content: "<p>Les émissions mondiales de CO2 ont atteint 40,6 gigatonnes en 2025, un record historique. L'Inde et l'Asie du Sud-Est portent l'essentiel de la hausse, tandis que l'Union européenne et les États-Unis voient leurs émissions baisser respectivement de 3 % et 1,5 %.</p><p>Le charbon reste le principal responsable, représentant 40 % des émissions. Les scientifiques du GIEC rappellent que pour limiter le réchauffement à 1,5 °C, les émissions mondiales doivent baisser de 43 % d'ici 2030.</p><p>Paradoxalement, la capacité installée en énergies renouvelables a également battu un record en 2025, avec 600 gigawatts supplémentaires de solaire et éolien. Mais cette croissance verte n'arrive pas à compenser l'augmentation de la demande mondiale en énergie, tirée par l'industrialisation rapide des pays émergents.</p><p>Le rapport appelle les pays du G20 à tripler leur objectifs de réduction d'émissions avant la COP31 de São Paulo en novembre. Il préconise notamment la fin des nouvelles centrales à charbon et un prix mondial du carbone d'au moins 100 dollars la tonne d'ici 2030.</p>",
      imageUrl: "https://images.unsplash.com/photo-1611735341450-74dc9b2fcbcc?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Cheminées d'usine émettant de la fumée dans un ciel gris",
      author: "Audrey Garric",
      categoryId: planete.id,
      tags: JSON.stringify(["CO2", "Réchauffement climatique", "Énergies renouvelables", "GIEC"]),
      publishedAt: new Date("2026-03-21T06:00:00"),
    },
    {
      title: "La Grande Barrière de corail subit son sixième épisode de blanchissement massif",
      slug: "grande-barriere-corail-blanchissement-massif",
      excerpt: "Les relevés aériens montrent que 80 % des récifs sont touchés, un niveau sans précédent attribué aux températures océaniques record.",
      content: "<p>L'Autorité du parc marin de la Grande Barrière de corail a confirmé l'étendue du blanchissement : 80 % des 3 000 récifs sont affectés, contre 60 % lors de l'épisode précédent en 2024. Les températures de surface de la mer de Corail dépassent de 2,5 °C les moyennes saisonnières.</p><p>Les scientifiques alertent sur le risque de mortalité massive si les conditions ne s'améliorent pas rapidement. « Au-delà de quatre semaines de stress thermique, le corail ne peut pas récupérer », prévient le professeur Terry Hughes de l'université James Cook.</p><p>L'Australie, sous pression internationale, a annoncé un plan d'urgence de 300 millions de dollars australiens pour tenter de préserver les zones les moins touchées. Ce plan inclut des techniques de « super-coraux » résistants à la chaleur, développés en laboratoire et replantés sur les récifs les plus endommagés.</p><p>L'UNESCO a annoncé une réunion extraordinaire pour examiner si la Grande Barrière doit être classée « patrimoine en péril ». Une décision que l'Australie avait réussi à éviter en 2023 grâce à ses engagements climatiques, mais qui semble inévitable si les dommages actuels se confirment.</p>",
      imageUrl: "https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Récif corallien sous-marin avec des poissons tropicaux colorés",
      author: "Martine Valo",
      categoryId: planete.id,
      tags: JSON.stringify(["Corail", "Réchauffement climatique", "Océan", "Biodiversité"]),
      publishedAt: new Date("2026-03-18T08:00:00"),
    },
    {
      title: "L'Amazonie a perdu 12 000 km² de forêt en 2025, malgré les promesses du Brésil",
      slug: "amazonie-deforestation-2025-bresil",
      excerpt: "Le taux de déforestation repart à la hausse après deux ans de baisse, mettant en péril les engagements climatiques brésiliens.",
      content: "<p>Les données satellitaires de l'INPE (Institut national de recherche spatiale) révèlent une augmentation de 22 % de la déforestation en Amazonie brésilienne par rapport à 2024. Les incendies volontaires pour l'élevage bovin et la culture du soja restent les principales causes.</p><p>Le président Lula, qui avait promis « zéro déforestation » d'ici 2030, fait face à une pression croissante du lobby agricole au Congrès. Les ONG environnementales dénoncent un « recul dramatique » de la politique de protection forestière.</p><p>L'accord de libre-échange entre l'Union européenne et le Mercosur, suspendu depuis 2023 justement en raison des engagements insuffisants sur la déforestation, est à nouveau en discussion. Bruxelles a prévenu que le texte ne pourrait être signé que si le Brésil revenait aux niveaux de déforestation de 2022.</p><p>Les peuples autochtones, première ligne de défense de la forêt amazonienne, ont déposé une plainte devant la Cour interaméricaine des droits de l'homme contre le gouvernement brésilien pour absence de protection de leurs territoires. Ils demandent la démarcation urgente de 120 nouvelles terres indigènes.</p>",
      imageUrl: "https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Forêt tropicale amazonienne vue du ciel avec une rivière sinueuse",
      author: "Bruno Meyerfeld",
      categoryId: planete.id,
      tags: JSON.stringify(["Amazonie", "Déforestation", "Brésil", "Forêt tropicale"]),
      publishedAt: new Date("2026-03-16T12:00:00"),
    },
    {
      title: "Tensions autour de Taïwan : Pékin multiplie les manœuvres navales dans le détroit",
      slug: "taiwan-chine-manoeuvres-navales-detroit",
      excerpt: "L'armée chinoise a déployé un nombre record de navires et d'avions militaires autour de l'île, provoquant une vive réaction de Washington et de Tokyo.",
      content: "<p>Pendant quatre jours, la marine chinoise a mené des exercices d'ampleur inédite dans le détroit de Taïwan et autour de l'île, mobilisant 70 navires et 120 avions. Pékin qualifie ces manœuvres de « réponse légitime » à la visite d'un sénateur américain à Taipei.</p><p>Les États-Unis ont renforcé leur présence navale dans la région avec le déploiement du porte-avions USS Gerald Ford. Le Japon a relevé son niveau d'alerte militaire. Taïwan a activé ses systèmes de défense antimissile.</p><p>Cette escalade intervient dans un contexte de tensions commerciales persistantes entre Pékin et Washington. L'administration américaine a annoncé la semaine dernière de nouvelles restrictions sur les exportations de semi-conducteurs avancés vers la Chine, aggravant les friction entre les deux puissances.</p><p>L'Union européenne, qui a considérablement durci sa position sur la Chine ces deux dernières années, a convoqué l'ambassadeur chinois à Bruxelles pour exprimer sa « préoccupation grave » face à ces manœuvres militaires. Elle appelle au dialogue et au respect du droit international maritime.</p>",
      imageUrl: "https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Navires de guerre en formation sur l'océan",
      author: "Frédéric Lemaître",
      categoryId: international.id,
      tags: JSON.stringify(["Taïwan", "Chine", "Géopolitique", "Diplomatie"]),
      publishedAt: new Date("2026-03-16T20:00:00"),
    },
    {
      title: "La tech européenne lève un montant record de 45 milliards d'euros en 2025",
      slug: "tech-europeenne-levees-fonds-record-2025",
      excerpt: "L'écosystème start-up du continent rattrape son retard, porté par l'intelligence artificielle, la deeptech et la transition énergétique.",
      content: "<p>Selon le rapport annuel d'Atomico, les start-up européennes ont levé 45 milliards d'euros en 2025, soit une hausse de 35 % par rapport à 2024. L'intelligence artificielle concentre à elle seule 30 % des investissements, avec des tours de table spectaculaires pour Mistral AI (2 milliards), Aleph Alpha (1,5 milliard) et DeepL (800 millions).</p><p>Paris se classe deuxième hub européen derrière Londres, avec 8,5 milliards levés, devant Berlin (6,2 milliards) et Stockholm (3,1 milliards).</p><p>La deeptech — intelligence artificielle, biotechnologies, énergie propre, spatial — représente désormais 45 % des montants levés, contre 30 % il y a cinq ans. Cette évolution reflète une maturation de l'écosystème européen, qui se distingue de plus en plus de la Silicon Valley par sa forte composante scientifique.</p><p>Les investisseurs américains ont participé à 38 % des tours de table européens de plus de 50 millions d'euros, preuve de l'attractivité croissante du continent. Reste un défi de taille : retenir ces champions une fois passé le stade de la croissance, plusieurs licornes ayant choisi de s'introduire en bourse à New York plutôt qu'à Paris ou Francfort.</p>",
      imageUrl: "https://images.unsplash.com/photo-1531297484001-80022131f5a1?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Espace de travail moderne dans une start-up technologique",
      author: "Alexandre Piquard",
      categoryId: economie.id,
      tags: JSON.stringify(["Start-up", "Intelligence artificielle", "Investissement", "Tech"]),
      publishedAt: new Date("2026-03-15T10:00:00"),
    },
    {
      title: "Procès des PFAS : l'État condamné pour inaction face aux polluants éternels",
      slug: "proces-pfas-etat-condamne-inaction",
      excerpt: "Le tribunal administratif de Lyon a reconnu la responsabilité de l'État dans la contamination par les substances per- et polyfluoroalkylées dans la vallée de la chimie.",
      content: "<p>Le jugement, qualifié d'« historique » par les plaignants, établit que l'État a manqué à son obligation de protection en ne régulant pas les rejets industriels de PFAS malgré les alertes scientifiques répétées depuis 2015.</p><p>Le tribunal ordonne à l'État de mettre en place un plan de dépollution dans un délai de six mois et d'indemniser les 2 000 habitants de la zone contaminée. Le ministère de la Transition écologique a annoncé faire appel.</p><p>Les PFAS (substances per- et polyfluoroalkylées, souvent appelés « polluants éternels ») se décomposent très lentement dans l'environnement et s'accumulent dans les organismes vivants. Ils sont associés à des risques accrus de cancers, de perturbations hormonales et de maladies cardiovasculaires.</p><p>La vallée de la chimie, au sud de Lyon, abrite plusieurs usines qui utilisent des PFAS depuis les années 1960. Des mesures effectuées en 2022 avaient révélé des taux de contamination dans les nappes phréatiques locales jusqu'à cent fois supérieurs aux nouvelles normes européennes. Ce jugement pourrait ouvrir la voie à des recours similaires dans d'autres zones industrielles en France.</p>",
      imageUrl: "https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Usine chimique avec des tuyaux et des installations industrielles",
      author: "Stéphane Foucart",
      categoryId: societe.id,
      tags: JSON.stringify(["PFAS", "Pollution", "Justice", "Environnement"]),
      publishedAt: new Date("2026-03-14T14:00:00"),
    },
    {
      title: "NBA : Victor Wembanyama élu joueur le plus utile de la saison à 22 ans",
      slug: "nba-wembanyama-mvp-saison",
      excerpt: "Le Français des San Antonio Spurs devient le plus jeune MVP européen de l'histoire de la NBA, confirmant son statut de joueur générationnel.",
      content: "<p>Avec des moyennes de 28,5 points, 12,3 rebonds et 3,8 contres par match, Victor Wembanyama a dominé la saison régulière et mené les Spurs à la quatrième place de la conférence Ouest. Il devance Luka Dončić et Jayson Tatum dans les votes.</p><p>« Victor est le futur de ce sport, mais il est aussi son présent », a déclaré le coach Gregg Popovich. Le joueur de 22 ans devient le premier Français élu MVP de la NBA.</p><p>Les statistiques de Wembanyama défient les lois habituelles du basket. Sa combinaison de taille (2,24 m), de vitesse, d'adresse à trois points (38 %) et de défense à périmètre sont sans précédent dans l'histoire de la ligue. Les analystes le comparent à une fusion entre Kareem Abdul-Jabbar et Kevin Durant.</p><p>Côté Spurs, la saison se poursuit avec les play-offs où San Antonio affrontera Oklahoma City au premier tour. Pour la première fois depuis l'ère Duncan, la franchise texane est considérée comme prétendante sérieuse au titre, portée par son prodige français et une équipe jeune et talentueuse.</p>",
      imageUrl: "https://images.unsplash.com/photo-1546519638-68e109498ffc?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Joueur de basketball effectuant un dunk spectaculaire",
      author: "Clément Guillou",
      categoryId: sport.id,
      tags: JSON.stringify(["NBA", "Wembanyama", "Basketball", "MVP"]),
      publishedAt: new Date("2026-03-16T04:00:00"),
    },
    {
      title: "Intelligence artificielle : GPT-5 relance le débat sur la conscience des machines",
      slug: "gpt-5-debat-conscience-machines",
      excerpt: "Le dernier modèle d'OpenAI affiche des capacités de raisonnement inédites, poussant philosophes et neuroscientifiques à redéfinir les frontières de l'intelligence.",
      content: "<p>GPT-5, dévoilé début mars, réussit des tests de raisonnement abstrait jusqu'ici réservés aux humains, notamment le test de compréhension causale de Kahneman et les épreuves de théorie de l'esprit. Ces performances relancent un vieux débat : la machine peut-elle « comprendre » ou ne fait-elle que simuler ?</p><p>« Nous devons distinguer intelligence fonctionnelle et conscience phénoménale », nuance la philosophe Catherine Malabou. « Un système peut résoudre des problèmes complexes sans éprouver quoi que ce soit. »</p><p>OpenAI a publié un rapport technique de 200 pages détaillant l'architecture de GPT-5, entraîné sur un corpus de 50 000 milliards de tokens incluant pour la première fois des données provenant de simulations physiques et de raisonnement formel. Le modèle peut générer et exécuter du code en temps réel pour résoudre des problèmes mathématiques complexes.</p><p>La Commission européenne a immédiatement annoncé une évaluation de GPT-5 au regard du règlement sur l'IA, entré en vigueur en 2025. Si le modèle est classé « à risque général », OpenAI devra soumettre à l'Agence européenne de l'IA un rapport de transparence détaillé et se plier à des audits réguliers.</p>",
      imageUrl: "https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Réseau de neurones artificiels en visualisation 3D",
      author: "David Larousserie",
      categoryId: sciences.id,
      tags: JSON.stringify(["Intelligence artificielle", "OpenAI", "Philosophie", "Recherche"]),
      publishedAt: new Date("2026-03-12T09:00:00"),
    },
    {
      title: "Sécheresse en Espagne : les réservoirs d'eau au plus bas depuis trente ans",
      slug: "secheresse-espagne-reservoirs-eau-plus-bas",
      excerpt: "La Catalogne et l'Andalousie font face à une crise hydrique sans précédent, avec des restrictions d'eau drastiques imposées aux particuliers et aux agriculteurs.",
      content: "<p>Les réservoirs espagnols ne sont remplis qu'à 28 % de leur capacité, le niveau le plus bas depuis 1995. La Catalogne, où les réserves ne dépassent pas 16 %, a interdit le remplissage des piscines et limité la consommation domestique à 200 litres par personne et par jour.</p><p>L'agriculture, qui représente 80 % de la consommation d'eau du pays, est la première touchée. Les producteurs d'olives et d'agrumes anticipent des pertes de récolte de 40 à 60 %.</p><p>Barcelone, qui avait déjà connu une crise similaire en 2023, a accéléré la construction d'une deuxième usine de dessalement, qui devrait être opérationnelle en 2027. La ville a également lancé un programme de réutilisation des eaux grises pour l'arrosage des espaces verts.</p><p>Le gouvernement espagnol a déclaré l'état d'urgence hydrologique dans cinq bassins versants et débloqué deux milliards d'euros pour financer des infrastructures d'urgence. Des experts hydrologues prévenaient depuis dix ans que l'Espagne était l'un des pays européens les plus vulnérables au changement climatique ; les événements actuels confirment ces prévisions.</p>",
      imageUrl: "https://images.unsplash.com/photo-1485470733090-0aae1788d5af?w=800&q=80&auto=format&fit=crop",
      imageAlt: "Sol fissuré d'un réservoir d'eau asséché",
      author: "Sandrine Morel",
      categoryId: planete.id,
      tags: JSON.stringify(["Sécheresse", "Espagne", "Eau", "Agriculture"]),
      publishedAt: new Date("2026-03-13T11:00:00"),
    },
  ];

  for (const article of articles) {
    await prisma.article.upsert({
      where: { slug: article.slug },
      update: {
        title: article.title,
        excerpt: article.excerpt,
        content: article.content,
        imageUrl: article.imageUrl,
        imageAlt: article.imageAlt,
        author: article.author,
        tags: article.tags,
      },
      create: article,
    });
  }

  // Utilisateur de test
  const passwordHash = await hash("password123", 12);
  await prisma.user.upsert({
    where: { email: "lecteur@lemonde.fr" },
    update: {},
    create: {
      name: "Jean Dupont",
      email: "lecteur@lemonde.fr",
      passwordHash,
    },
  });

  console.log(`Seed terminé : 8 catégories, ${articles.length} articles, 1 utilisateur test`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
